<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWAZ0v6Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWAZ0v6Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWAZ0v6Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWAZ0v6Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWAZ0v6Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'WAZ0v6Z',
    'container.build_id' => '5e73a2cc',
    'container.build_time' => 1610334836,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWAZ0v6Z');
