<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG2LK6ah\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG2LK6ah/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG2LK6ah.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG2LK6ah\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG2LK6ah\App_KernelDevDebugContainer([
    'container.build_hash' => 'G2LK6ah',
    'container.build_id' => 'cea188f1',
    'container.build_time' => 1610336926,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG2LK6ah');
