<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoxgHAM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoxgHAM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUoxgHAM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUoxgHAM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUoxgHAM\App_KernelDevDebugContainer([
    'container.build_hash' => 'UoxgHAM',
    'container.build_id' => 'd7ef7f38',
    'container.build_time' => 1610329898,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoxgHAM');
